--- #YAML:1.0
name:               XML-DifferenceMarkup
version:            1.04
abstract:           XML diff and merge
author:
    - Vaclav Barta <vbar@comp.cz>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::LibXML:  1.70
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
