# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-DifferenceMarkup
version:      1.00
version_from: lib/XML/DifferenceMarkup.pm
installdirs:  site
requires:
    XML::LibXML:                   1.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
