---
abstract: 'XML diff and merge'
author:
  - 'Vaclav Barta <vbar@comp.cz>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-DifferenceMarkup
no_index:
  directory:
    - t
    - inc
requires:
  XML::LibXML: 1.70
version: 1.05
