--- #YAML:1.0
name:                XML-DifferenceMarkup
version:             1.02
abstract:            XML diff and merge
license:             ~
author:              
    - Vaclav Barta <vbar@comp.cz>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    XML::LibXML:                   1.58
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
